### ISSUE TITLE
Non key property ("Id") in Dto problem

### ISSUE THREAD

**Issue by Alikhll** [bit-foundation/bit-framework#1]
I've got a Dto that has a property named "Id" but it's not a Key and I'm gonna update it's value later using jaydata, but unfortunately it's way seems make some un handled problems

**Comment by ymoradi** [comment]
It seems to be a bug in our "IsKey" method of "IPropertySymbolExtensions" class. We've to improve it. It returns true in case the name of prop is Id or ClassName + Id (for example CustomerId) or prop with [Key] attribute. We may ignore first and second rules when there is another prop with key attribute in our Dto class.

For example:

```
public class CustomerDto : IDto
{
     public int Id {get; set;}
     [Key]
     public Guid CId {get;set;}
}
```

IsKey() method should return false for Id property in this case.

**Comment by ymoradi** [comment]
Sorry, I was closing #2
