### ISSUE TITLE
Automapper configuration method not working

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#101]
Hi, 
Does anyone know that why Configure method not fired? 

```
public class TestDtoEntityMapperConfiguration : IDtoEntityMapperConfiguration
    {
// this method not fired at all
        public virtual void Configure(IMapperConfigurationExpression mapperConfigExpression)
        {
            mapperConfigExpression.CreateMap<Customer, CustomerDto>()
                .ForMember(c => c.FullName, cnfg => cnfg.MapFrom(c => c.FirstName + " " + c.LastName));
        }
    }
```

**Comment by ysmoradi** [comment]
It gets fired if you:
1- Register it using [RegisterDtoEntityMapperConfiguration](https://github.com/bit-foundation/bit-framework/blob/master/Apps/BitChangeSetManager/AspNet/AppStartup.cs#L126-L127)
2- Send request to a DtoSetController/DtoController which uses IDtoEntityMapper

**Comment by behzad888** [comment]
How can I use it in api controllers?

**Comment by ysmoradi** [comment]
You can inject it by declaring a property in your controller as following:

public IDtoEntityMapper<CustomerDto, Customer> Mapper { get; set; }

**Comment by behzad888** [comment]
Thanks in advance
