### ISSUE TITLE
User subject and User Id are same

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#103]
Why user-subject and user-id are same in the User Service? 
Please see [this line](https://github.com/bit-foundation/bit-framework/blob/4fcfe3551a8addbcd046d4922d87c1e1f5d79521/src/Server/Bit.IdentityServer/Implementations/UserService.cs#L42), 
Also I have  same claim values???

**Comment by ysmoradi** [comment]
You don't have to inherit from UserService and you can directly inherit from UserServiceBase. To make thing easy in UserService, we accept one user id from a developer and fill all common claims with that user id. Of course, a developer can assign individual values to claim types based on application requirements.
