### ISSUE TITLE
An exception occurs when calling SyncContext Xamarin forms 

### ISSUE THREAD

**Issue by Jaguel** [bit-foundation/bit-framework#105]
Hi.

I try to use SyncContext in ISyncService but in cases when I have for example List[Guid] an exception occurs saying cannot convert from List[object] to List[Guid]. In other cases it works fine, The error seems to happen in ToDto extension method. Please check this out. 

version : 1.0.7
Xamarin forms

Thank you for the effort.

**Comment by ysmoradi** [comment]
This issue is now resolved.
