### ISSUE TITLE
Convert entity model to ts file

### ISSUE THREAD

**Issue by Salamesalehpour** [bit-foundation/bit-framework#106]
hi

With which part of the bit-framework can convert a entity model to ts file?
please help me

thanks

**Comment by ysmoradi** [comment]
Bit doesn't generate ts code for entities, it generates code for dto classes instead. See https://docs.bit-framework.com/docs/bit-server-side/odata.html

Clone https://github.com/ysmoradi/BitSampleApp
It uses msbuild task to generate codes for you.

**Comment by Salamesalehpour** [comment]
thanks dear yaser
