### ISSUE TITLE
grouping in radGrid

### ISSUE THREAD

**Issue by hoda-mohammadi** [bit-foundation/bit-framework#11]
I want to group some rows and show the group in my radgrid and if I expand group, show all related rows and if I collapse group , hide all related rows   
how can i do this in this radGrid?
examples: http://demos.telerik.com/kendo-ui/grid/aggregates

**Comment by ymoradi** [comment]
When you create data source from your queryable (in-memory, odata, indexed-db) by calling .asKendoDataSource() use following syntax: 

`.asKendoDataSource({ group: [{ field: 'Name' }] })`

If you like to let your users to define grouping, simply use groupable=true on your rad grid view, for example:

`<rad-grid-view groupbable=true ></rad-grid-view>`

**Comment by ysmoradi** [comment]
Last commit link was made by a mistake.
