### ISSUE TITLE
DefaultRandomStringProvider.GetRandomString() dose not work correctly

### ISSUE THREAD

**Issue by dotnetzoom** [bit-foundation/bit-framework#112]
**Describe the bug**
GetRandomString method implamentation in DefaultRandomStringProvider class dose not work correctly

**To Reproduce**
use this code `defaultRandomStringProvider.GetRandomString(4)`

**Expected behavior**
We expect to get a randomize string with length of 4, but we receive a  string with length of 28 

**Cause**
because `Substring()` method used  instead of `Remove()` method at this [line](https://github.com/bit-foundation/bit-framework/blob/b43bf070841ca1c69b3ce990bfa51679b8dc1e69/src/Server/Bit.Owin/Implementations/DefaultRandomStringProvider.cs#L18)
```
return result.Substring(length);
```

**Solution**
We need to use the following code
```
return result.Remove(length);
or
return result.Substring(0, length);
```

**Comment by ysmoradi** [comment]
Closed by #115
