### ISSUE TITLE
DefaultAppEnvironmentsProvider improvement

### ISSUE THREAD

**Issue by dotnetzoom** [bit-foundation/bit-framework#113]
It would be great if DefaultAppEnvironmentsProvider gets integrated with `Microsoft.Extensions.Configuration.IConfiguration` and read setting from **appsettings.json**

It would be nice if app gets reloaded after environments.json changes too.

**Comment by ysmoradi** [comment]
[This](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/DotNetCoreTestApp) is a sample app which uses appSettings.json
Just call
```AspNetCoreAppEnvironmentsProvider.Current.Init();```
[Sample](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/DotNetCoreTestApp/AppStartup.cs#L37)
