### ISSUE TITLE
OData operation configuration's optional parameter is not working properly 

### ISSUE THREAD

**Issue by Alikhll** [bit-foundation/bit-framework#12]
```
       [Function]
       [Parameter("firstNumber", typeof(int))]
       [Parameter("secondNumber", typeof(int), isOptional: true)]
       public virtual async Task<int> Sum(CancellationToken cancellationToken, [FromODataUri]int firstNumber, [FromODataUri]int secondNumber = 10)
       {
           return firstNumber + secondNumber;
       }
```
As I tested, generated JavaScript & TypeScript codes of html client are ok, but when I take a look at generated $metadata of DefaultAutoEdmBuilder, I see no IsOptional on that and I see bad request exception when I pass firstNumber, but I get the result when I pass both parameters

**Comment by ymoradi** [comment]
Can't find out why! Please write E2E test for this after resolving the issue.

**Comment by ymoradi** [comment]
Function's optional parameter has serious problems, but there is no problem with actions
```
        [Action]
        [Parameter("firstNumber", typeof(int))]
        [Parameter("secondNumber", typeof(int), isOptional: true)]
        public virtual async Task<int> Sum(ODataActionParameters parameters, CancellationToken cancellationToken)
        {
            return (int)parameters["firstNumber"] + (parameters.ContainsKey("secondNumber") ? (int)parameters["secondNumber"] : 1);
        }
```

**Comment by ysmoradi** [comment]
We've to develop custom Web API Action Selector, and this is not a high priority for us at the moment. We're going to develop custom parameter binder and custom action selector within the next major release of bit.
