### ISSUE TITLE
Close BitDatePicker when selected date

### ISSUE THREAD

**Issue by aliebrahimi2015** [bit-foundation/bit-framework#129]
hi
how to close  popup when selected a date or click in bitdatepicker ?
thanks

**Comment by ysmoradi** [comment]
I call it auto close functionality. By selecting a day, the picker gets closed automatically. That's it?

**Comment by aliebrahimi2015** [comment]
yes 
when click on datepicker auto close not work for me
but When I click outside the control it closes
why?

**Comment by aliebrahimi2015** [comment]
> 
> 
> I call it auto close functionality. By selecting a day, the picker gets closed automatically. That's it?

yes
when click on datepicker auto close not work for me
but When I click outside the control it closes
why?

**Comment by ysmoradi** [comment]
It's a expected behavior based on current implementation. As I labeled, we need enhancements for this.

**Comment by ysmoradi** [comment]
@aliebrahimi2015 Now you can use Bit 1.3.90 release.
