### ISSUE TITLE
Insert | Update >> Let's raise an exception in case of unexpected behavior 

### ISSUE THREAD

**Issue by Alikhll** [bit-foundation/bit-framework#13]
Consider following scenarios:
1- Update from Dto into model when property of model is internal somehow!
2- Raise an exception when we insert an entity which has a version somehow!

**Comment by ysmoradi** [comment]
Fixed by https://github.com/bit-foundation/bit-framework/pull/14 & https://github.com/bit-foundation/bit-framework/blob/master/BitTools/BitCodeAnalyzer/SystemAnalyzers/PropertyAccessorsInternalModifierAnalyzer.cs
