### ISSUE TITLE
sequence contains no elements

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#135]
I got an error in [this line](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/Bit.WebApi/Implementations/SwaggerDefaultValuesOperationFilter.cs#L29) as `sequence contains no elements` because I am using FromUri Model Binding.

When using FromUri Model Binding, duplicate items can appear as items can be passed as URI parameters or querystrings. In this case we can add a custom operation filter to remove the duplicates.

so we need to check duplicates. 

see [this](https://github.com/behzad888/bit-framework/commit/5445bb931aecb760d8abe2439f9d36fd88f006e5)

**Comment by ysmoradi** [comment]
Could you please provide a small repo for this? Thanks in advance.

**Comment by behzad888** [comment]
You can see [this repo](https://github.com/behzad888/bit-swagger-small-repo/)

**Comment by behzad888** [comment]
In Addition, I need to define `Route` for all of APIs because swagger UI cannot track them.

**Comment by ysmoradi** [comment]
> In Addition, I need to define `Route` for all of APIs because swagger UI cannot track them.

That repo is using Bit 1.4
If you update it to Bit 1.5, web api's default routing mechanism will get back to work.

I'm gonna write a test for that. Then I'll merge your PR.
Thanks in advance.
