### ISSUE TITLE
Not a valid calendar for given culture in bit date picker in release mode

### ISSUE THREAD

**Issue by mo-kml** [bit-foundation/bit-framework#140]
I'm trying to use Bit date picker v1.8.0.
But in release mode with Linker config i got this error.

> Not a valid calendar for the given culture.

I tried to skip these assemblies in linker config but still this error shows up.

```
  <assembly fullname="Bit.CSharpClient.Controls">
    <type fullname="*" />
  </assembly>
  <assembly fullname="System.Core">
    <type fullname="*" />
  </assembly>
  <assembly fullname="NodaTime">
    <type fullname="*" />
  </assembly>
```

What assembly should i skip in linker config to make this control work?

**Comment by ysmoradi** [comment]
https://github.com/bit-foundation/bit-framework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples.Android/LinkerConfig.xml
