### ISSUE TITLE
Null complex property issue with typescript client

### ISSUE THREAD

**Issue by rezarozbahani** [bit-foundation/bit-framework#146]
**Describe the bug**
When there is a null complex type in response, I receive following error:
Cannot read property 'Value' of null.

**To Reproduce**
Return a null complex inside a dto object.

**Expected behavior**
It should return a dto with a property of that complex type which is null

**Screenshots / Logs / Exception details**
In
```js
var itemKeyFn = function(di) {
     if (typeof di["Value"] === "undefined")
          return undefined;
     if (di["Value"] === null)
          return null;
...
};
```
di itself is null!

**Bit Server side products (Bit.OData, Bit.Signalr, etc)**
- Bit nuget package's version. 2.0
- ASP.NET or ASP.NET Core? ASP.NET Core
- Operating System. Win 7 SP1
- .NET Core, mono or .Net Framework? NET 4.6.1

**Bit CSharp client (If applicable)**
N/A

**Bit TypeScript/JavaScript client (If applicable)**
- Bit npm package's version. 2.0
- Mobile, desktop or web app? Web App
- Which browser? (If applicable) Chrome 73
- Which framework? For example angular 7

**Additional context**
N/A

**Comment by ysmoradi** [comment]
JayData 1.5.19 has been released. You can get it to solve this issue in your own app.
