### ISSUE TITLE
Provide prepared where statement in sql query parts

### ISSUE THREAD

**Issue by rezarozbahani** [bit-foundation/bit-framework#147]
**Is your feature request related to a problem? Please describe.**
I need a property in SqlQueryParts which returns prepared where.
For example instead of
```sql
where Id = @Param1
```
returns
```sql
where Id = 1
```

**Describe the solution you'd like**
I've following code which works like a charm!
```cs
sqlQuery.WhereClause = Regex.Replace(sqlQuery.WhereClause, "@Param[0-9]", e =>
{
     string paramName = e.Value.Replace("@", "");
     object value = sqlQuery.Parameters[paramName];
     if (value is string strValue)
          return $"'{value}'";
     return value.ToString();
});
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ysmoradi** [comment]
It's too risky if you use it without caution!
