### ISSUE TITLE
No need to GetAllInterfaces

### ISSUE THREAD

**Issue by mjebrahimi** [bit-foundation/bit-framework#148]
There is no need to `GetAllInterfaces` method [here](https://github.com/bit-foundation/bit-framework/blob/48059e667704ceec565957d74671f3ceadf0b7ab/src/Server/Bit.Data/Extensions/IDependencyManagerExtensions.cs#L95).
Method [Type.GetInterfaces](https://docs.microsoft.com/en-us/dotnet/api/system.type.getinterfaces?view=netframework-4.8) return all the interfaces implemented or inherited by the current type.

**Comment by ysmoradi** [comment]
PR?

**Comment by mjebrahimi** [comment]
Done. #150
