### ISSUE TITLE
Swagger Schema FullTypeName error

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#152]
I have an error in swagger:
```
Conflicting schemaIds: Identical schemaIds detected for types ABC.IContract and DEF.IContract. See config settings –  “UseFullTypeNameInSchemaIds”
```
Do you mind using ` doc.UseFullTypeNameInSchemaIds();` in [default api config](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/Bit.WebApi/Extensions/OpenApiExtensions.cs#L31)?

If no, It would be helpful if you can tell me why and how can I handle multiple `Dto` with the same name?

**Comment by ysmoradi** [comment]
You can do something like this:

```cs
httpConfiguration.EnableSwagger(c =>
{
...
     c.ApplyDefaultApiConfig(httpConfiguration);
     c.UseFullTypeNameInSchemaIds(); // You've access to swagger config
}).EnableBitSwaggerUi();
```
Anyway, it seems interesting. Could you please send a PR?
