### ISSUE TITLE
Security Persist Info Option

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#153]
After opening a DbConnection the password is removed from the connection string for security reasons so that you can pass around the connection object without exposing the password. Sometimes we need need to set 'Persist Security Info' option by `true`.  

After reading [`GetDbTransaction`](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/Bit.Data/DefaultDbConnectionProvider.cs) methods I think there is something wrong with `Security Persist Info` option in the connection string. Although, In these methods, there is nothing to check it. It just checked by `_connections.ContainsKey(connectionString)`.

Any Idea?

**Comment by ysmoradi** [comment]
Thanks for your attention. We've received the same complain from other customers which are using channels other than github issue. I'll notify you as soon as my PR gets ready for this.

**Comment by behzad888** [comment]
Thanks in advance! 

but I think `ExtendedSingle` causes a bug too.

Imaging, there is the same connection string with many keys in `environment.json` for modular scenarios. 
`ExtendedSingle` in `GetDbConnection` method makes an error like `Multiple values for single key`.

**Comment by ysmoradi** [comment]
Could you please provide more details about the scenario? I think there won't be any issue.
If you decide to use db connection provider with ef 6 db context or dapper for example, you've to pass it's transaction to underlying db context. (By calling dbContext.Database.Use). if you use db context provided by dependencyManager.RegisterEfCoreDbContext or dependencyManager.RegisterDbContext, you won't see that exception.

**Comment by behzad888** [comment]
I have many modules that contain a DbContext by **EF core** with a connection string. therefore, they contain `IAppModule` and `IAppEvents`. I need to ensure the database was created (By calling dbContext.Database.EnsureCreated) because of  EF global filtering. Actually, I want to add a global filter into `OnModelCreating`. 

First, `ExtendedSingle` method could not cover it because all modules have own connection string. but, sometimes they need to define the same connection string with a different key.
```json
...
       {
        "Key": "Key1",
        "Value": "Data Source=192.168.2.2;Initial Catalog=Db1;Integrated Security=False;Persist Security Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True;"
      },
      {
        "Key": "Key2",
        "Value": "Data Source=192.168.2.2;Initial Catalog=Db1;Integrated Security=False;Persist Security Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True"
      },
      {
        "Key": "Key3",
        "Value": "Data Source=192.168.2.3;Initial Catalog=Db2;Integrated Security=False;Persist Security Info=False;User ID=sa;Password=123;MultipleActiveResultSets=True"
      },
...
```

Next, I have an error `'The connection is already in a transaction and cannot participate in another transaction.'`. Although, It has been registered by `RegisterEfCoreDbContext` before.

hope this enough :)

**Comment by ysmoradi** [comment]
I'd recommend you to add [application name](https://www.connectionstrings.com/use-application-name-sql-server/) to your connection string, so you can have better profiling over your sql commands in sql profiler & you won't see this issue any more.
You can also get app name in your sql commands by running
```sql
select app_name()
```
For transaction one, could you please provide a simple repo?
Thanks in advance.

**Comment by behzad888** [comment]
Thank you! Let me try on Saturday
