### ISSUE TITLE
Error in bitDateTimePicker 2.7.0

### ISSUE THREAD

**Issue by honamina** [bit-foundation/bit-framework#164]
I used bitcontrols version 2.6 and every thing was OK since I updated controls to last version with nuget. BOOM!!! My app not working more.
I tried and tried something and finally find this :
1- When I use x:Name="DatePicker1", VS raises this error on build :
       Type BitDateTimePicker not found in xmlns https://bit-framework.com
I need to define a name for control to use it in code-behind to set/calculate something.

2- Ok, I removed then x:Name and VS compiled app , but on opening activity this error raises:

![3](https://user-images.githubusercontent.com/34470290/63436483-04db2d00-c43e-11e9-90c7-0d5d2c48546b.png)
 I download your sample and project from GitHub and tried to run your sample. But your sample has same problems.

This is my xaml page:

![1](https://user-images.githubusercontent.com/34470290/63436644-4a97f580-c43e-11e9-9834-20daa7853923.png)

![2](https://user-images.githubusercontent.com/34470290/63436651-4cfa4f80-c43e-11e9-8867-bb6f934bdfc8.png)

Bit.CSharpClient.Controls 2.7.0
Xamarin.Forms 4.1.0.673156
Android/IOS

**Comment by ysmoradi** [comment]
For your first problem about BitDatePicker could not be found in https://...
You've to call Init as followings:

https://github.com/bit-foundation/bit-framework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples/App.xaml.cs#L15

For your second problem, let me check. I'm so sorry about that.

**Comment by honamina** [comment]
Hello dear friend.
I did what you said to add initiate line to app.xaml.cs.
But error still raises.
Thank for help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ysmoradi** [comment]
Which error? I mean the build error. The second error which you get at runtime, I solved that and you'll receive the fix in next release

**Comment by honamina** [comment]
I’m talking about first error. I get same error yet on build .
[cid:image003.png@01D55A71.42FE8B40]

[cid:image006.png@01D55A71.42FE8B40]

**Comment by ysmoradi** [comment]
But you can build the csharp client sample without any modification, yeah?

**Comment by ysmoradi** [comment]
What's your visual studio version? For example 16.2

**Comment by honamina** [comment]
I did not test you sample code again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by honamina** [comment]
Exactly. Version is 16.2.3

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by honamina** [comment]
Are you live in Iran?
I can send my phone-no to call.

**Comment by ysmoradi** [comment]
Please wait for new release. It's going to be there soon. If problem exists, we can have a talk over Skype

**Comment by ysmoradi** [comment]
https://github.com/bit-foundation/bit-framework/releases/tag/v2.7.1
