### ISSUE TITLE
Sequence more than one elements

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#167]
I have an issue as `Sequence more than one elements`  on this [line](https://github.com/bit-foundation/bit-framework/blob/master/src/Server/Bit.Data.EntityFrameworkCore/Implementations/EntityFrameworkCoreMapperConfiguration.cs#L17) when using Disctionary<string, string> for the entity property type.

**Comment by ysmoradi** [comment]
Oops! and what's your type?

**Comment by behzad888** [comment]
property type could be anything!
``` c#
public virtual Dictionary<TKey, TValue>  MyField {get; set;}
```

**Comment by ysmoradi** [comment]
Not all property types are supported in Dto classes. To use Dictionary<string,object>, you can implement IOpenType as following:
```
public class MyDto : IDto, IOpenType
{
    public int Id {get;set;}
    public Dictionary<string, object> Properties { get; set; }
}
```
