### ISSUE TITLE
Authentication not supported in asp .net MVC

### ISSUE THREAD

**Issue by Rajatnigam9** [bit-foundation/bit-framework#168]
**Authentication not supported**
I want the basic HTTP authentication in my web API which is not supported in Asp .net MVC. I have tried all the possible fix to do so but it neither showing a pop-up for authentication key to enter nor added the input field for the same.

**Comment by ysmoradi** [comment]
By ASP.NET MVC, you mean ASP.NET MVC 5 or ASP.NET Core MVC?

**Comment by Rajatnigam9** [comment]
ASP.NET MVC 5

**Comment by Rajatnigam9** [comment]
Following is the nested class need to be implemented: 


 private class AddRequiredHeaderParameter: IOperationFilter
        {
            public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
            {
                if (operation.parameters == null)
                    operation.parameters = new List<Parameter>();

                operation.parameters.Add(new Parameter
                {
                    name = "Authorization",
                    @in = "header",
                    type = "string",
                    required = true
                });
            }
        }


 and finally used in Enable Swagger: c.OperationFilter<AddRequiredHeaderParameter>();
