### ISSUE TITLE
Roslyn Analyzer for Dto|ComplexType classes without default public constructor.

### ISSUE THREAD

**Issue by rypedram** [bit-foundation/bit-framework#17]
Sending Dtos and Complex Types to clients is possible in Web API OData even for those without public default constructor, but its not possible when client sends data to Web API OData Server. This causes developers to making a mistake ,So we've to enfore having public default ctor for dtos & complex types.

**Comment by ysmoradi** [comment]
Thanks @rypedram Please develop an analyzer for this, but do not develop any lines of code to detect which class is either Dto or Complex type. I'll develop those part.

**Comment by ysmoradi** [comment]
We're applying this to Dto & Complex types only.
