### ISSUE TITLE
Error for assembly reference for bit framework

### ISSUE THREAD

**Issue by elham9449** [bit-foundation/bit-framework#172]
**Describe the bug**
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	XLS0419	Undefined CLR namespace. The 'clr-namespace' URI refers to a namespace 'Bit.CSharpClient.Controls' that could not be found.			

and 

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		Position 26:14. Type bitControls1:BitDateTimePicker not found in xmlns https://bit-framework.com		

I have tried these three assembly references:
xmlns:bitControls="clr-namespace:Bit.CSharpClient.Controls;assembly=Bit.CSharpClient.Controls"
 xmlns:noda="clr-namespace:NodaTime;assembly=NodaTime"
             xmlns:bitControls1="https://bit-framework.com"

**Comment by ysmoradi** [comment]
To make https://bit-framework.com namespace work, you've to put [this code](https://github.com/bit-foundation/bit-framework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples/App.xaml.cs#L15) in your app.xaml.cs

**Comment by elham9449** [comment]
Thank's for your help. It works well!

**Comment by ysmoradi** [comment]
You're always welcome!
