### ISSUE TITLE
Can't Use BitDateTimePicker in Xamarin Andorid

### ISSUE THREAD

**Issue by AliDeV7** [bit-foundation/bit-framework#181]
Hello

I do every Steps in this [link](https://www.dotnettips.info/post/2955/%D8%AA%D9%82%D9%88%DB%8C%D9%85-%D8%B4%D9%85%D8%B3%DB%8C-%D8%AF%D8%B1-xamarin-forms), but after i want use BitDateTimePicker in my project i get this error :
The Type bitControls:BitDatePicker in not found.
My Code : https://i.ibb.co/WtpNB4f/Error.jpg
Please Help me,I need this Calendar.Thanks So much 👍

**Comment by ysmoradi** [comment]
Are you able to build & run [original sample](https://github.com/bit-foundation/bit-framework/tree/master/Samples/CSharpClientSamples/Controls.Samples)?
and make sure about [this](https://github.com/bit-foundation/bit-framework/blob/master/Samples/CSharpClientSamples/Controls.Samples/Samples/App.xaml.cs#L15) too.

**Comment by AliDeV7** [comment]
it works now!Thanks

I wonder, is there any way that i use Calendar without popup? i mean, i want exactly This(Calendar) in my page 

![image](https://user-images.githubusercontent.com/50456620/71764680-27a74300-2f00-11ea-8b22-eda5d7ceb142.png)

**Comment by ysmoradi** [comment]
It's not possible at the moment, but if you really need this feature, we can consider it in our upcoming release

**Comment by AliDeV7** [comment]
Yes I really need this and thinks its necessary for piker to have this option 
so I'm waiting for next Update :)

Thanks for Answering

**Comment by AliDeV7** [comment]
Hello Again :)

I Need this Future, I need To Know how many Days Take you Add this Option to Your Project? 
I need PersianCalendarView :(

**Comment by ysmoradi** [comment]
The new version has been released
