### ISSUE TITLE
radGrid column titles are LTR instead of RTL

### ISSUE THREAD

**Issue by hoda-mohammadi** [bit-foundation/bit-framework#29]
I've written this style to make rad grid column titles RTL

```
    thead.k-grid-header > tr > .k-header {
        text-align: right;
    }
```

**Comment by rypedram** [comment]
for using RTL style you have to use  "k-rtl" class
if you want to change all of your element inside your page you can do like this 
<body class="k-rtl"> and if you want to change specific element you can do just like this 
<element class="k-rtl">
