### ISSUE TITLE
add best practice for select Primary key by developers

### ISSUE THREAD

**Issue by develqi** [bit-foundation/bit-framework#3]
hi

please limit selection primary key types by developers in bit-framework. for example add IEntityWithDefaultIntKey like IEntityWithDefaultGuidKey and remove IEntityWithDefaultKey<int> generic interface. the best practice for primary key types are Int or Guid. other types should not be selected by developers.

best regards.

**Comment by ymoradi** [comment]
I'm not a fan of Int16 as a key for performance considerations (?!), but in some apps you'd prefer to use Int64 as a key.
