### ISSUE TITLE
Console.set_Title error on running sample on IIS

### ISSUE THREAD

**Issue by mo-kml** [bit-foundation/bit-framework#32]
I was trying to run the bitChangeSetManager on IIS (Windows 10.14393) and I got this error:

```
IOException: The handle is invalid.
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +1093
   System.Console.set_Title(String value) +112  ....  AppStartup.cs:34
```

There was no problem on iis express.

**Comment by ysmoradi** [comment]
See https://github.com/bit-foundation/bit-framework/commit/7e7082907936c7e4b2f8fbed77447ad7c708435d
