### ISSUE TITLE
negative value problem in decimal object

### ISSUE THREAD

**Issue by Pedram-Ahmadpour** [bit-foundation/bit-framework#37]
Into **IndexedDb** when we save minus value like **"-1000"**; saved value is **"0000000000000000000000000-1000"**. So, the problem is here when  ***decimal*** use regex  ***/^0+(?=\d)/*** to clear extra zeros; result is some thing like this : **"0-1000"**
Try **/^0+(?!\\.)/** instead of **/^0+(?=\d)/**.

**Comment by ysmoradi** [comment]
Wow! It's a very nice issue! Thanks @Pedram-Ahmadpour, I'm gonna check that

**Comment by ysmoradi** [comment]
Fixed via https://github.com/bit-foundation/jaydata/commit/0d87483dc2c0ae963d118769c18517e969afcc46
