### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by miladra** [bit-foundation/bit-framework#38]
In the foundation project there are some reference like 
```
/// <reference path="../../foundation.core.htmlclient/foundation.core.d.ts" />
/// <reference path="../../foundation.core.htmlclient/foundation.core.d.ts" />
/// <reference path="../../foundation.viewModel.htmlclient/foundation.model.context.d.ts" />
```
to some files, but those file does not exist.

and also the foundation.core project does not exist too.
```
/// <reference path="../foundation.core/typings.d.ts" />
```

**Comment by mo-kml** [comment]
Hi
its about your path.
every "../" means a folder above from original path.
please check your path.

**Comment by miladra** [comment]
dear mo-kml
I have installed all of those projects. The files foundation.core.d.ts , foundation.core.d.ts ,... and the project foundation.core does not exist, i search these files in The whole of project,
Are these files created automatically?

**Comment by ysmoradi** [comment]
@miladra Yes, those files are being generated automatically, foundation.core.d.ts is a result of building foundation.core.csproj for example. You can build bit solution using instructions provided in read me file. In case you encounter any problem, you're welcome to submit an issue right here :)

**Comment by ysmoradi** [comment]
https://github.com/bit-foundation/bit-framework/blob/master/README.md
