### ISSUE TITLE
merge all repositories after Ef core find support

### ISSUE THREAD

**Issue by Alikhll** [bit-foundation/bit-framework#5]
Ef core has supported find linq method eventually in latest of it's version and I think it's time to merge all repositories to a one repo
let's do it soon ;))

**Comment by Alikhll** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/

**Comment by ysmoradi** [comment]
Closed by https://github.com/bit-foundation/bit-framework/commit/d44c01ffbd1b79ad205d88f387db2b9cb7533e0b
