### ISSUE TITLE
fetch api using angular cli with proxy config fails to get token in response!

### ISSUE THREAD

**Issue by kordeviant** [bit-foundation/bit-framework#82]
using this code although validation gets passed but token is not present in response.
```
const loginData = `scope=openid+profile+user_info&grant_type=password&username=${data.username}&password=${data.password}`;
        const myHeaders = new Headers({
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'Content-Length': loginData.toString().length.toString(),
            'Authorization': 'Basic Rmxhd2luZ28tUmVzT3duZXI6c2VjcmV0'
        });
        try {
            const token = await fetch('http://localhost:4200/core/connect/token', {
                method: 'POST',
                body: loginData,
                headers: myHeaders
            });
            console.log(token);
        } catch (e) {
            console.log('there was an error');
            console.log(e);
            throw e;
        }
```
angular request no token in response | swagger request that returns token
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/22198402/31719720-3c6eb716-b421-11e7-90f2-f9b7a25ee3ba.png)  |  ![image](https://user-images.githubusercontent.com/22198402/31719746-52f2c284-b421-11e7-870e-0c81501589c2.png)

only diffrence is that angular is using angular-cli proxy config on this route, and other parts of bit framework work ok with this proxy config.

**Comment by ysmoradi** [comment]
Could you please upload har files for both requests?
Remove
```
'Authorization': 'Basic Rmxhd2luZ28tUmVzT3duZXI6c2VjcmV0'
```
and try again

**Comment by kordeviant** [comment]
when i remove authorization i successfully get error no client ,

[har files.zip](https://github.com/bit-foundation/bit-framework/files/1394706/har.files.zip)

**Comment by ysmoradi** [comment]
You don't have to write complete url. 'core/connect/token' is enough I think. (This is not a reason of your error although)

Ok. I see no client_id in your request.

I think in swagger, you've not send client_id and secret too. This is working in swagger for a reason I'm not aware about, maybe you've provided client_id and secret in your previews attempts and now it works because of that.

**Comment by kordeviant** [comment]
in swagger, i chose basic auth that's why client_id and secret are being inserted into the request as authorization header

**Comment by ysmoradi** [comment]
Ooops! I got what you say.

**Comment by ysmoradi** [comment]
Clear your browser and run fetch request in developer console of main .net app (for example in swagger ui, instead of running that in angular app). For example if your .net app is hosted under http://localhost:26001 & your angular app is hosted under http://localhost:4200, try that code in console of chrome under 26001 (Without angular cli proxy)

**Comment by kordeviant** [comment]
```
        var loginData2 = 'scope=openid+profile+user_info&grant_type=password&username=1&password=1&client_id=Flawingo-ResOwner&client_secret=secret';
        var myHeaders2 = new Headers({
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            Accept: 'application/json',
        });
       
        window.fetch('/core/connect/token', {
                method: 'POST',
                body: loginData2,
                headers: myHeaders2
            }).then((token)=>{console.log(token);});
```
in my swagger this also return no result
in timing tab sais request is not finished yet 
![image](https://user-images.githubusercontent.com/22198402/31722372-c3c8d5e6-b428-11e7-9f79-c34b21292f74.png)

**Comment by kordeviant** [comment]
solved !!! fetch actually does not get the full response not until you call its methods that work for stream data ;

```
var loginData2 = 'scope=openid+profile+user_info&grant_type=password&username=1&password=1&client_id=Flawingo-ResOwner&client_secret=secret';
        var myHeaders2 = new Headers({
            'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            Accept: 'application/json',
        });
       
        window.fetch('/core/connect/token', {
                method: 'POST',
                body: loginData2,
                headers: myHeaders2
            }).then((res)=>{
				return res.json()
			}).then((res)=>{
			 console.log(res)
			});
```

**Comment by ysmoradi** [comment]
Something like this would be come in handy:

```typescript
        @Log()
        public async login(userName: string, password: string, client_id: string, secret: string, scope = ["openid", "profile", "user_info"]): Promise<{ access_token: string, expires_in: number, token_type: string }> {

            const loginData = `scope=${scope.join("+")}&grant_type=password&username=${userName}&password=${password}&client_id=${client_id}&client_secret=${secret}`;

            const loginHeaders = new Headers({
                "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                "Content-Length": loginData.length
            });

            const response = await fetch("core/connect/token", {
                method: "POST",
                body: loginData,
                headers: loginHeaders
            });

            const token: { access_token: string, expires_in: number, token_type: string } = await response.json();

            return token;
        }
```
