### ISSUE TITLE
Can't return Task<List<Guid>> in controller

### ISSUE THREAD

**Issue by Alikhll** [bit-foundation/bit-framework#9]
consider the following code
```
        [Function]
        [Parameter("categoryId", typeof(Guid))]
        public virtual async Task<Guid[]> GetlocationIdsByCategoryId([FromODataUri]Guid categoryId, CancellationToken cancellationToken)
        {
            return await _categoryInLocationsRepository.GetAll().Where(c => c.ProductCategoryId == categoryId).Select(c => c.LocationId).ToArrayAsync(cancellationToken);
        }
``` 
above code makes these error
`  Build:Type 'string' does not satisfy the constraint 'Entity'.`

**Comment by ymoradi** [comment]
Based on my tests, and based on line 147 of sample jaydata code located in https://github.com/jaystack/odata4-webapi-endpoint/blob/development/WebApi_2_2_OData_4/client/JayDataContext.js which is 
`SFunction1: { type: $data.ServiceFunction, returnType: 'Edm.String', params: [{ name: 'number', type: 'Edm.Int32' }] }`
We've no real problem with this at runtime. There is a small problem with jaydata defenitions. We've to remove T extends Entity generic constraint from $data.Queryable of jaydata in line 56 of jaydata.d.ts @Alikhll Could you please do this in https://github.com/bit-foundation/jaydata/blob/development/jaydata.d.ts and then report the test results here?

**Comment by ymoradi** [comment]
There is a problem with string[] (or any [] like types) in code generator, I'm gonna fix that. But There might be no other problem with List, IEnumerable, IQueryable etc.

**Comment by Alikhll** [comment]
it seems solve this problem, thanks bro
