### ISSUE TITLE
Not Acceptable Error

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#93]
I have 'Not Acceptable(406)' error when I use DtoController<>,
My $ metadata is known but my EntitySet is not known.

Is there any idea to fix it?

**Comment by ysmoradi** [comment]
Could you please write your DtoController & Dto codes here?

**Comment by behzad888** [comment]
Sure!
```
public class PrincipalsController : DtoController<PrincipalDto> { }
```

```
    [Serializable]
    public class PrincipalDto : IDto
    {        
        public int Id { get; set; }
        public string Name{ get; set; }

    }
```

**Comment by ysmoradi** [comment]
I just copied following codes to end of [odata sample](https://github.com/bit-foundation/bit-framework/blob/master/Samples/ODataSamples/CustomerDtoControllerSample/AppStartup.cs) and it worked fine when I opened http://localhost:9000/odata/swagger/ui/index#!/Principals/Principals_GetPrincipalByKey

```cs
    public class PrincipalDto : IDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class PrincipalsController : DtoController<PrincipalDto>
    {
        [Function]
        public SingleResult<PrincipalDto> GetPrincipal(int key)
        {
            return SingleResult.Create(
                new PrincipalDto[]
                {
                    new PrincipalDto
                    {
                        Id = key,
                        Name = key.ToString()
                    }
                }
            .AsQueryable());
        }
    }
```

I attached the sample too. Just execute "dotnet run" in command line next to csproj file and open mentioned link.
[ODataSamples.zip](https://github.com/bit-foundation/bit-framework/files/1942929/ODataSamples.zip)

**Comment by ysmoradi** [comment]
Note that there is no need to Serializable attribute.
