### ISSUE TITLE
Could not load type  System.ComponentModel.DataAnnotations.MetadataTypeAttribute

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#95]
When I used swagger or OData, I received an interesting exception:

```
Could not load type 'System.ComponentModel.DataAnnotations.MetadataTypeAttribute' from assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```
I saw https://github.com/dotnet/corefx/issues/16101 ,So,  I there any changes? Thanks in advance.

**Comment by ysmoradi** [comment]
Following is a asp.net core 2.1 with .net core 2.1 + bit + odata + postgre sql + entity framework core.
You can read and test docs provided at https://docs.bit-framework.com and then you can test them on this project.

[AspNetCoreDotNetCoreBitSampleApp.zip](https://github.com/bit-foundation/bit-framework/files/1947300/AspNetCoreDotNetCoreBitSampleApp.zip)

Take a look at following notes at csproj file:

```xml
    <!-- To use private build of DotNetCore which is a result of https://github.com/dotnet/corefx/pull/29121, you've to use following tags: RuntimeIdentifier & PackageConflictPreferredPackages -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PackageConflictPreferredPackages>Microsoft.Private.CoreFx.NETCoreApp;runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp;$(PackageConflictPreferredPackages)</PackageConflictPreferredPackages>
```

**Comment by ysmoradi** [comment]
Note that our support for .net core is in early stage, but you can develop your apps using asp.net core 2 & **full .net framework**
After we supported .net core, you'll have a easy one step automatic migration to get .net core (-:

**Comment by behzad888** [comment]
I also have this error in Web API samples

**Comment by ysmoradi** [comment]
@behzad888 Sorry for my late response. I've not seen any notification for your reply in GitHub notifications center! Do you've got the same problem with this project too? https://github.com/bit-foundation/bit-framework/tree/master/Samples/WebApiSamples/6WebApiDotNetCoreHost

**Comment by behzad888** [comment]
Yes, I have, so I had to use net461 in startup project.

**Comment by ysmoradi** [comment]
Do you've .net core sdk 2.1 installed (.NET Core SDK 2.1.300-rc1)?

**Comment by behzad888** [comment]
Yes, 
Note that, I'm using win7. does have any problem?

**Comment by ysmoradi** [comment]
I don't think so. But let's move forward using .net 461, we can change target when .net core 2.2 released with bit changes. They've accepted our PR for 2.2 milestone.

**Comment by ysmoradi** [comment]
The PR gets merged into corefx. You can use dotnet core sdk nightly builds to test your app.
