### ISSUE TITLE
DtoController NotFound

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#96]
Hi there,

I have a module with new class library project and use `DtoController` and `DtoSetController` in it. When I call $metadata with its `ODataServiceBuilder` I can see all of `EntitySets` and etc of that, but I can't use any of that.

I think the OData router `ODataConventionModelBuilder` does not work properly
 while the same controllers in the startup project are ok.

Do you have in mind?

**Comment by ysmoradi** [comment]
https://stackoverflow.com/questions/47609240/how-to-have-modular-dependency-registration-in-different-projects-in-bit-framewo

**Comment by behzad888** [comment]
Good job!

**Comment by ysmoradi** [comment]
[AspNetCoreDotNetCoreBitSampleAppWithModuleSupport.zip](https://github.com/bit-foundation/bit-framework/files/1947382/AspNetCoreDotNetCoreBitSampleAppWithModuleSupport.zip)

This sample app has separated module.
