### ISSUE TITLE
Secure binary serialization is not supported on this platform

### ISSUE THREAD

**Issue by behzad888** [bit-foundation/bit-framework#97]
I have an error like "Secure binary serialization is not supported on this platform."
I think this happens when I have #95 error again. I think when I used complicated queries I have this error!
Does have any idea?

I would be appreciated if you can help to fix it,
Than you!

**Comment by behzad888** [comment]
Complicated queries like 
```
select * from Customers inner join Cities on Id = CustomerId where IsActive = 1 /*1 means true. It comes from your server side linq query: Where(c => c.IsActive == true))*/

```

Bit version: v1.0.4

ASP.net core

dotnet versions : 
dotnet-sdk-2.1.300-preview2-008533-win-x64
dotnet-sdk-2.1.300-preview1-008174-win-x64

corefx version:
4.5.0-preview3-26513-0 -> runtime.win-x64

OS: Windows 7, 8.1, 10

**Comment by behzad888** [comment]
StackTrace: in version 1.0.5
```
 Bit.OData.Implementations.DefaultWebApiODataControllerActionSelector.SelectAction(HttpControllerContext controllerContext) in C:\\Users\\b.abbasi\\Downloads\\bit-framework-1.0.5\\bit-framework-1.0.5\\src\\Server\\Bit.OData\\Implementations\\DefaultWebApiODataControllerActionSelector.cs:line 106\r\n   at System.Web.OData.Routing.ODataActionSelector.SelectAction(HttpControllerContext controllerContext)\r\n   at System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer.<>c__DisplayClass7_0.<System.Web.Http.Controllers.IHttpActionSelector.SelectAction>b__0()\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace)" | string

```

**Comment by ysmoradi** [comment]
@behzad888 Sorry for my late response. I've not seen any notification for your reply in GitHub notifications center! Could you please copy/paste entire visual studio's output here? Thanks in advance.

**Comment by ysmoradi** [comment]
It seems that you were running ODataSamples of bit on top of .net core. As you might know, entity framework 6 which is being used at that sample is not compatible with .net core (yet). I submit you that sample which works with entity framework core and asp.net core & .net core. Note that you've to install .net core 3 preview 1+
[ODataSamples.zip](https://github.com/bit-foundation/bit-framework/files/3025271/ODataSamples.zip)
